---@class TLLFuelConfiguration
---@field add_fuel boolean
---@field fuel_category_configurations table<string, TLLFuelCategoryConfiguration>
---@field new fun(): TLLFuelCategoryConfiguration
---@field toggle_add_fuel fun(self: TLLFuelConfiguration)
---@field add_fuel_category_config fun(self: TLLFuelConfiguration, fuel_category: string)

---@class TLLFuelCategoryConfiguration
---@field selected_fuel string?
---@field fuel_amount number
---@field new fun(): TLLFuelCategoryConfiguration
---@field change_selected_fuel_and_check_overcap fun(self: TLLFuelCategoryConfiguration, string): boolean
---@field get_max_fuel_amount fun(self: TLLFuelCategoryConfiguration)
---@field set_fuel_amount fun(self: TLLFuelCategoryConfiguration, number)

Exports = {}

-- Fuel category configuration

TLLFuelCategoryConfiguration = {}

function TLLFuelCategoryConfiguration:new()
    local new_object = {
        selected_fuel = nil, -- nil or string
        fuel_amount = 0 -- 0 to 3 stacks of selected_fuel
    }
    setmetatable(new_object, self)
    self.__index = self
    return new_object
end

--- Changes which fuel type is selected in this fuel category. New trains in blueprints generated by the schedule table will request this fuel.
--- Returns true if this resulted in lowering the fuel_amount due to it exceeding there maximum amount of fuel that can possibly be loaded into a train.
--- Returns false otherwise. 
---@param selected_item string
---@return boolean 
function TLLFuelCategoryConfiguration:change_selected_fuel_and_check_overcap(selected_item)
    -- If the current config.selected_fuel == selected_item, deselect it
    if self.selected_fuel == selected_item then
        self.selected_fuel = nil
        self:set_fuel_amount(0)
        return false
    else
        self.selected_fuel = selected_item
        local new_max_value = self:get_max_fuel_amount()
        if new_max_value < self.fuel_amount then
            self:set_fuel_amount(new_max_value)
            return true
        else
            return false
        end
    end
end

function TLLFuelCategoryConfiguration:get_max_fuel_amount()
    if self.selected_fuel then
        return game.item_prototypes[self.selected_fuel].stack_size * 3
    else
        return 1
    end
end

---@param amount number
function TLLFuelCategoryConfiguration:set_fuel_amount(amount)
    self.fuel_amount = amount
end


-- Fuel configuration

TLLFuelConfiguration = {}

function TLLFuelConfiguration:new()
    local new_object = {
        add_fuel = true,
        fuel_category_configurations = {}
    }
    setmetatable(new_object, self)
    self.__index = self
    return new_object
end

function TLLFuelConfiguration:toggle_add_fuel()
    self.add_fuel = not self.add_fuel
end

---@param fuel_category string
function TLLFuelConfiguration:add_fuel_category_config(fuel_category)
    self.fuel_category_configurations[fuel_category] = TLLFuelCategoryConfiguration:new()
end


Exports.TLLFuelConfiguration = TLLFuelConfiguration

return Exports